### PR TITLE
Adds sample usage to README

### PR DESCRIPTION
**Pull request by msneeden**
Adds a simple usage scenario to the README. Let me know if you'd like to see any changes to format, examples, etc.

### CODE REVIEW

**Comment by yosida95** [comment]
Nice improvements! Would you use `.. code-block:: go` directive instead of using `::` to ensure snippets are highlighted.

**Comment by msneeden** [comment]
Sure! Updated to use `.. code-block:: go`

**Comment by yosida95** [comment]
First `code-block` (above import statement) is unnecessary, so please delete it. Additionally, please meld two commits in the PR into single commit.

**Comment by msneeden** [comment]
Removed first code-block statement, melded changes into one commit.

**Comment by yosida95** [comment]
I really appreciate your contributions!

**Pull request merged**
