### PR TITLE
Created jenkins queue API stuffs. Go fmt ran

### PR DESCRIPTION
**Pull request by arranubels**
I have squashed and fmt'd. However I believe the URL path is required for this to work.

### CODE REVIEW

**Comment by arranubels** [comment]
Removed as requested.

**Comment by yosida95** [comment]
Thank you for taking your time.

http://play.golang.org/p/8mPNm6tBdb
This is the proof of that `/api/json` suffix is necessary.

**Comment by yosida95** [comment]
Oh, function document is not for GetQueue but for GetJob.

**Comment by arranubels** [comment]
hahah oops. That's a big one. Check now.

**Comment by yosida95** [comment]
Thank you.  I really appreciate your contribution!

**Pull request merged**
